//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportId { get; set; }
        public int TaskID { get; set; }
        public int AccountID { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
        public double Effort { get; set; }
        public double Overtime { get; set; }
        public string Descrition { get; set; }
        public string Status { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Task Task { get; set; }
    }
}
