//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public int AccountId { get; set; }
        public int ProjectId { get; set; }
        public string Role { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Project Project { get; set; }
    }
}
